name: Deploy Project 7

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🏗️
        run: |
          cd project7/ballot-next
          npm install
          npm run build
          touch out/.nojekyll

      - name: Deploy to Branch 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: project7/ballot-next/out
          target-folder: project7/ballot-next
          branch: gh-pages
